[title]
content = "なんでもないや (movie ver.)"
format = "jp"
size = 24

[subtitle]
exist = true
content = "君の名は。"
format = "jp"
size = 14

[artist]
exist = true
content = "RADWIMPS"
format = "jp"
size = 17

[cover]
exist = true
name = "cover"
format = "jpg"

[[other_info]]
former_text = "作词:"
former_format = "zh-cn"
later_text = "野田洋次郎"
later_format = "jp"

[[other_info]]
former_text = "作曲:"
former_format = "zh-cn"
later_text = "野田洋次郎"
later_format = "jp"

[groups]
num = 3
format = [ "romaji", "jp", "zh-cn" ]