[title]
content = "Lemon"
format = "jp"
size = 24

[subtitle]
exist = true
content = "日剧《非自然死亡》主题曲"
format = "zh-cn"
size = 14

[artist]
exist = true
content = "米津玄師"
format = "jp"
size = 17

[cover]
exist = true
name = "cover"
format = "jpg"

[[other_info]]
former_text = "作词:"
former_format = "zh-cn"
later_text = "米津玄師"
later_format = "jp"

[[other_info]]
former_text = "作曲:"
former_format = "zh-cn"
later_text = "米津玄師"
later_format = "jp"

[[other_info]]
former_text = "编曲:"
former_format = "zh-cn"
later_text = "米津玄師/室屋光一郎"
later_format = "jp"

[groups]
num = 3
format = [ "romaji", "jp", "zh-cn" ]